- client/package.json
- client/src/store/socket.ts
- client/src/types.ts
- client/tsconfig.json
- client/yarn.lock
- server/src/index.ts
- server/src/listener/admin.agenda.ts
- server/src/model/chat/client.ts
- server/src/model/chat/common.ts
- server/src/model/chat/index.ts
- server/src/model/chat/server.ts
- server/src/model/index.ts
- server/src/types.ts
- server/tsconfig.json
- socket/helpers.ts
- socket/types.ts
Support strict typing & intellisense throughout server & client sockets.
Can be used by adding `ServerToClientEvents` & `ClientToServerEvents` by a generic parameter when initializing a `Server` or a `Client` instance. Type `BiseoClient`, `BiseoServer`, and `BiseoSocket` is also available as aliases.
> feat(interface): Add type sharing feature between server & client

- .gitignore
- server/.gitignore
- server/nodemon.json
- server/package.json
- server/src/env.ts
- server/src/index.ts
- server/src/lib/error.ts
- server/src/service/admin.agenda.ts
- server/src/utils/logger.ts
- yarn.lock
https://github.com/winstonjs/winston 을 사용해 커스텀 로거를 추가합니다.
https://github.com/sparcs-kaist/taxi-back 에서 싱싱하게 수입해 왔습니다. 아니, 조금 수정을 가해서 택시 로거의 상위호환이예요 😄 
제가 도입하려는 logger에는 두 가지 특징이 있습니다.
1. 로그 레벨: 두 가지 로그 레벨을 사용합니다.
a. "info" : 일반적인 정보(API 접근 등) 기록을 위해 사용합니다.
b. "error" : 오류 메시지를 기록하기 위해 사용합니다.
2. 로그 출력 위치: production 여부에 따라 로그 출력 위치가 달라집니다.
a. "production" : 모든 로그는 파일 시스템에 저장됩니다. 오류 메시지는 콘솔로도 출력됩니다.
b. "development" 또는 "test" : 모든 로그는 콘솔에 출력됩니다.
예제로 현재 사용되고 있는 서비스 로직들에서 `console.log`와 `console.error` 함수들을 각각 `logger.info`와 `logger.error`로 교체했습니다.
- 콘솔에 로그 레벨, 타임스탬프와 함께 로그가 출력됩니다.
> <img width="606" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/46402016/7bf0dcc4-1374-439d-90d5-583842827041">
- 파일시스템에 로그 레벨, 타임스탬프와 함께 로그가 저장됩니다.
> <img width="540" alt="image" …
> Introduce custom logger

- interface/agenda/common.ts
Fixes #41 
typescript에 discriminated union으로 취급되어 type narrowing이 일어나게 하기 위해서 타입 수정했습니다.
- `z.enum(["ongoing"])` -> `z.literal("ongoing")`
- `AgendaStatus` 타입 변경
기존 코드에 미치는 영향은 없습니다.
```typescript
// Agenda type
const agenda = { ... } as Agenda;
if (agenda.status === "ongoing") {
agenda // <- inferred as TerminatedAgenda
}
```
> fix(type): fix agenda status type

- client/src/components/molecules/ChatInput.tsx
resolve #79 
chat에서 버튼을 눌러 전송하는 경우 입력했던 메세지가 그대로 남아있는 이슈
> fix(chat): setValue to null when sending by button

- client/src/components/molecules/ParticipantBar.tsx
resolve #255 
우선 소수점 아래 1 자리까지 표시되도록 만들었어요
> fix(ongoing): progress bar up to 1 decimal place

- client/src/components/organisms/Header.tsx
모달을 열어도 헤더 item select ui가 잘 작동해요
Resolves #263
> fix: selected header item on modal open

- .eslintrc
- client/src/components/pages/MainPage.tsx
- client/src/styles/background.ts
- client/src/styles/border.ts
- client/src/styles/color.ts
- client/src/styles/index.ts
- client/src/styles/layout.ts
- client/src/styles/round.ts
- client/src/styles/size.ts
- client/src/styles/spacing.ts
- client/src/styles/text.ts
- client/tsconfig.json
- pnpm-lock.yaml
> Init CSS tokens

- docker-compose.yml
It resolves #323 
Docker Compose에서 client(nginx 컨테이너)와 DB를 다른 네트워크로 분리하였습니다.
개발용 서버([biseo.dev.sparcs.org](biseo.dev.sparcs.org))에 배포하여 테스트 완료했습니다.
[기존]
client와 server, db가 같은 네트워크로 연결되어 있습니다.
[작업 후]
server와 db가 같은 네트워크에 연결되어 있습니다 (`frontend` 도커 네트워크)
client와 server가 같은 네트워크에 연결되어 있습니다 (`backend 도커 네트워크). client와 db는 직접적으로 같은 네트워크에 있지 않기 때문에, client에서 db에 접근할 수 없습니다.
> [FEAT] Docker Compose에서 client, db 네트워크 분리

- client/src/components/molecules/ChatInput.tsx
- client/src/components/molecules/ModalInnerTextBox.tsx
1. Resolve #152 by a7b5c0e328037871b3eb81f75b1239d8e6046cd9
ModalInnerTextBox와 비슷한 역할을 하던 ChatInput을 참고하여 만들었습니다.
2. Resolve #195 by cf69bf10b6286fad7ef06cbfff4fe274376bd8b5
ModalInnerTextBox와 ChatInput에 사용된 onKeyPress를 onKeyDown으로 대체하였습니다.
컴퓨터에서 한글을 입력하다보면 아랫쪽에 밑줄이 뜨는 것을 확인할 수 있습니다.
이는 한글이 조합 중이라는 의미로 한 문자를 완성하기 위해 입력이 이어질 수 있음을 의미합니다.
KeyboardEvent에서 현 상황이 조합 중인지를 확인하는 방법이 isComposing입니다.
이유는 모르겠으나 한글 입력 과정에서 KeyboardEvent를 받아오면 isComposing이 true인 것과 false인 것이 하나씩 생성되는데 true인 것이 마지막 글자만 잘린 상태로 오류를 야기합니다.
제 지식 내에서 최대한 다양한 상황을 시도해보았으나, **OS에 따라 문제가 일어날 수도 있다고 하니 Windows 사용하시는 분들이 직접 돌려보시면 좋겠습니다.**
[주 참고자료 - 현 이슈와 비슷한 상황을 서술한 블로그](https://velog.io/@corinthionia/JS-keydown%EC%97%90%EC%84%9C-%ED%95%9C%EA%B8%80-%EC%9E%85%EB%A0%A5-%EC%8B%9C-%EB%A7%88%EC%A7%80%EB%A7%89-%EC%9D%8C%EC%A0%88%EC%9D%B …
> Enter로 입력하기, onKeyPress 대체하기

- .eslintrc
It fixes #366
jsx를 사용할 때 prop을 object spread를 통해 전달하는 것을 허용합니다.
> [참조] jsx prop spreading을 허용하는 이유 (이슈 설명 참조)
> 1. jsx prop spreading을 금지하는 이유
> 	- https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md
> 	- 불필요하게 많은 prop이 커스텀 컴포넌트에 전달되는 것을 막고, 특정 컴포넌트가 받을 수 없는 타입의 prop을 전달하는 것을 막음
> 2. 규칙을 비활성화할 수 있는 이유
> 	- prop spreading을 사용하지 않으면 일일이 prop의 속성들을 전달해야 해 불편함
> 	- 커스텀 컴포넌트의 경우 typescript를 사용해 전달되는 prop의 타입을 강제하고 있음 -> 특정 컴포넌트가 받을 수 없는 타입의 prop이 전달되지 않음
저도 규칙 바꾸니 좋은 것 같아요 ㅎㅎ
> jsx prop spreading 허용

- client/src/components/atoms/TextArea.tsx
- client/src/components/molecules/ChatInput.tsx
- interface/src/admin/agenda/common.ts
- interface/src/agenda/template/common.ts
- interface/src/chat/client.ts
- interface/src/chat/common.ts
- interface/src/user/tag/common.ts
It fixes #242, fixes #228
1. 아래 이벤트들에 대해 string 길이 검증(min: 1, max: 255)을 적용했습니다. (#242)
- `chat.send`
- `admin.agenda.create`
- `agenda.template.create`
- `user.tag.create`
2. 채팅 입력 창에 최대 글자 수(500자)와 최대 높이(30%)를 설정하고, 줄이 길어지는 경우 스크롤을 추가했습니다. (#228) 
- 크로미엄 브라우저에서 보이는 스크롤바
- <img width="476" alt="image" src="https://github.com/sparcs-kaist/biseo/assets/46402016/96b63dd6-ff3e-4fc5-b910-d254ac2ce176">
- 파이어폭스 브라우저에서 보이는 스크롤바 (`::-webkit-scrollbar ` css 의사 요소은 크로미엄만 지원)
- (스크롤바에 커서를 두지 않았을 때)
- (스크롤바에 커서를 두었을 때)
- #309 : 사용자에게 텍스트 제한이 넘었음을 알려줄 수 있는 인터렉션 요소를 추가합니다.
- #375 : 투표 생성, 투표 템플릿, 유저 태그 생성 모달에서 입력값 검증을 추가합니다.
> 채팅 입력 글자수 제한

- client/src/services/chat/index.ts
Chat 리스너가 등록되지 않아 chat이 수신되지 않는 버그에 대한 핫픽스입니다.
> Fix chat receive bug

- packages/api/src/lib/error.ts
It fixes #419
biseo-api의 `libs/error.ts`에서 BiseoError 클래스를 Error 클래스를 extend해 사용하고 있는데, TypeScript 2.1부터 Error 클래스를 extend할 수 없다고 합니다(https://github.com/microsoft/TypeScript/issues/12123 이슈 참조).
사실 Error 클래스를 extend할 이유가 없어서(클라이언트에만 전달되는 에러입니다 - 감사해요 @SnowSuno ), BiseoError가 Error를 extend하지 않게 수정하였습니다.
- 없음
> BiseoError 생성 시 serialize 메서드가 존재하지 않음

- packages/web/src/components/organisms/EditAgendaModal.tsx
It closes #348 
투표 수정에서 설명을 수정하면 줄바꿈이 사라집니다.
지연언니가 문제를 찾아줬고
> 생성 모달은 textarea인 반면 수정 모달은 text라서 발생하는 문제로 보입니다.
해당 문제 해결하려고 EditAgendaModal에서 InputBox를 TextAreaInputBox로 바꿨습니다 
- 없음
> fix(editAgendaModal): change to TextAreaInputBox

- packages/web/src/components/organisms/AdminAgendaSection.tsx
- packages/web/src/components/organisms/OngoingAgendaModal.tsx
- packages/web/src/constants/phrases.ts
'진행 중인 투표'로 올바른 띄어쓰기로 워딩 통일.
It closes #402 
- 없음
> fix: unified Naming

- packages/web/src/components/molecules/Profile.tsx
- packages/web/src/components/organisms/Header.tsx
It closes #347 
p.s. eslint 짱이네용 근데 에러 해결을 조금 미루다가 커밋을 통으로 해버렸어요... 앞으로 나눠서 잘 커밋하겠습니당..
로그아웃 UI 제작
원래 1번째 알파벳이 보이는 버튼을 박스 형태의 div로 바꾸었고, 관련 부분 css 토큰화 형식으로 변경했습니다.
알파벳이 보이는 박스는 relative로, Profile UI는 absolute로 position 설정해서 Profile UI 위치를 박스 위치에 종속시켰습니다.
알파벳이 보이는 박스에 hover한 뒤에 아래 profile UI로 가면 hover 상태가 false가 되는 상황이어서 div로 알파벳이 보이는 박스와 profile UI를 모두 감싼 뒤에 해당 div에 setHover를 사용했습니다
도와주세요.. 모르겠어요 ㅠㅜㅠ
- [Done] Profile UI 위치 박스에 종속적으로 변경
- [TODO] 박스와 profile 사이의 간격 코드 수정 필요
위에 있는 알파벳 박스와 profile 창 사이의 gap 설정하면 gap을 지나는 도중에 hover가 false로 바뀌는 상황이라 우선 투명 div로 박스 아래 5px를 투명 div로 만들어서 묶어둔 상황 (뭔가 하드코딩 느낌이라 바꾸고 싶은데 방법을 모르겠어요,,,ㅠ)
> feat(profile): complete profile box UI

- packages/web/src/components/molecules/ModalInnerTextBox.tsx
It closes #375 
ChatInput에서 500자 제한한것과 동일하게
ModalInnerTextBox의 InputBox와 TextAreaInputBox에 maxLength 속성을 추가했습니다!
> Feat/Max Textlength

- packages/web/src/components/molecules/Profile.tsx
It closes #468
- 프로필에 나오는 username의 vertical alignment를 center 하였습니다.
- 만약 나중에 프로필의 디자인을 바꿔서 크기를 더 크게 만들게 된다면 그 안에 있는 elements들의 width, height, horizontal and vertical padding 등을 다시 수정하여서 맞추어야 할 것 같습니다.
> fix: vertically center username in profile popup

- packages/api/prisma/schema.prisma
It closes #464.
변수명을 `DATABASE_URL`로 통일합니다.
`pnpm dev` 하셨을 때 prisma에서 문제가 발생할 경우 터미널에서 아래 커맨드 한 번 실행해보시면 좋을 것 같습니다.
```
npx prisma migrate dev --schema {schema.prisma 파일 경로}
```
다른 파일에서 사용 중인 변수에는 문제가 없는지 추가적으로 확인해봐야 할 것 같습니다.
> fix: update .env.example

- packages/web/src/components/molecules/ModalInnerTextBox.tsx
It closes [#374](https://github.com/sparcs-kaist/biseo/issues/374)
다른 Text에는 명시적으로 필요하지 않은 필드라고 생각해서 style을 이용해서 적용했습니다
수정 전
수정 후 (24년 03월 27일)
- 없음
> fix: adjust '+' line height to one

- packages/web/src/components/atoms/Text.tsx
- packages/web/src/components/organisms/ChatSection.tsx
It closes #[465](https://github.com/sparcs-kaist/biseo/issues/465)
따로 피그마에 명시된 디자인이 없어서 중앙 정렬을 하였습니다.
고민 하나 했던건 side margin : auto vs text-align : center인데 직관적인 text-align을 사용했습니다.
개선 후
> fix: align 'loading' text to center

- packages/api/src/service/admin.agenda.ts
- packages/api/src/service/agenda.ts
- packages/interface/src/admin/agenda/common.ts
- packages/interface/src/agenda/common.ts
- packages/web/src/components/molecules/AgendaCard/AdminTerminatedAgendaCard.tsx
- packages/web/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx
- packages/web/src/utils/format.ts
It closes #483 .
종료된 투표 카드에 투표가 시작한 날짜를 표시합니다.
- 종료된 투표 중 최근 투표(24시간 내 or 오늘)와 그 이전 투표를 분리하는 divider를 추가합니다.
> feat: add start time on terminated agenda cards

- packages/api/src/listener/admin.agenda.ts
- packages/interface/src/admin/agenda/client.ts
- packages/interface/src/admin/agenda/server.ts
- packages/web/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx
- packages/web/src/services/admin-agenda.ts
It closes #490 
- 유저 모드와 투표 관리에서 Terminated agenda card의 우측 상단에 투표가 **종료된 날짜**를 표시합니다.
- 유저 모드에서 카드를 열었을 경우, 카드 하단에서 **투표가 종료된 일시**를 확인할 수 있습니다.
- 투표가 종료되자마자 바로 날짜가 표시되도록 state 업데이트 로직을 수정했습니다. 이 과정에서 `admin.agenda.statusUpdated`의 api 반환값이 일부 변경되었습니다.
- 없음
> feat: show end time on terminated agenda card

- packages/web/src/components/atoms/ToggleSwitch.tsx
- packages/web/src/components/molecules/AgendaCard/Group.tsx
- packages/web/src/components/organisms/AgendaSection.tsx
It closes #475 
종료된 투표 중 24시간 내 **시작된** 투표들만 필터링해주는 토글 스위치를 추가했습니다.
(브랜치명이 recently-started-agendas여야 할 것 같네요 😅 )
https://github.com/sparcs-kaist/biseo/assets/100757008/a0796c30-1822-4305-96dc-1fcef18a09c4
- 없음
> feat: recent agendas filtering

- packages/web/src/components/atoms/ToggleSwitch.tsx
- packages/web/src/components/molecules/AgendaCard/Group.tsx
- packages/web/src/components/organisms/AgendaSection.tsx
It closes #495 
새로고침을 하거나 다른 곳으로 navigate한 후 돌아와도 `최근 투표만` 옵션이 저장되어 있습니다.
https://github.com/sparcs-kaist/biseo/assets/100757008/c986e720-a309-4143-a518-bab4c27f07ec
- 없음
> feat: save recent agendas filter option

- packages/api/src/listener/agenda.ts
- packages/api/src/service/agenda.ts
- packages/interface/src/agenda/client.ts
- packages/interface/src/events.ts
- packages/web/src/components/atoms/Button.tsx
- packages/web/src/components/molecules/AgendaCard/OngoingAgendaCard.tsx
- packages/web/src/components/molecules/Choice.tsx
- packages/web/src/services/agenda.ts
- pnpm-lock.yaml
> feat: add edit vote feature
