sparcs-kaist/biseo

client/src/services/chat.ts, server/src/interface/admin/agenda/client.ts, server/src/interface/admin/agenda/index.ts, server/src/interface/admin/agenda/server.ts, server/src/interface/agenda/client.ts, server/src/interface/agenda/common.ts, server/src/interface/agenda/index.ts, server/src/interface/agenda/server.ts, server/src/interface/chat/client.ts, server/src/interface/chat/common.ts, server/src/interface/chat/index.ts, server/src/interface/chat/server.ts, server/src/interface/events.ts, server/src/interface/helpers.ts, server/src/interface/index.ts, server/src/interface/user/client.ts, server/src/interface/user/index.ts, server/src/interface/user/server.ts
- refactor(interface): simplify interface definition
- refactor(interface): strictly type event map
=> refactor(interface): improve interface structure & usage

server/src/interface/agenda/common.ts
add `voted` field to `OngoingAgenda` schema
to check if user voted
=> feat(agenda-interface): add `voted` field

client/src/socket/io.ts, client/src/socket/utils.ts
Improves readability and opts out unnecessary code by using functional inheritance.
=> feat(socket): refactor `BiseoSocket`

client/src/services/agenda.ts
=> feat(agenda): complete first draft

interface/admin/agenda/common.ts, server/src/listener/admin.agenda.ts, server/src/service/admin.agenda.ts
Codes about Admin-Agenda Back end
=> feat(admin-agenda): fix api fit to schema

client/src/components/atoms/BorderedBox.tsx, client/src/components/atoms/Box.tsx, client/src/components/atoms/Text.tsx, client/src/components/molecules/OptionVoteResult.tsx, client/src/components/molecules/VoteResult.tsx, client/src/components/organisms/AgendaCard.tsx, client/src/components/organisms/AgendaSection.tsx
This is a PR for developing minor UI design progression, and connecting the UI with the back-end, for the terminated agendas.
Resolves #35
=> Terminated Agenda UI - Logic Connect

client/src/components/atoms/BorderedBox.tsx, client/src/components/atoms/Box.tsx, client/src/components/atoms/Text.tsx, client/src/components/molecules/OptionVoteResult.tsx, client/src/components/molecules/VoteResult.tsx, client/src/components/organisms/AgendaCard.tsx, client/src/components/organisms/AgendaSection.tsx
=> Feat/admin UI display

client/src/assets/index.ts, client/src/assets/plusIcon.svg, client/src/components/atoms/BorderedBox.tsx, client/src/components/atoms/Button.tsx, client/src/components/atoms/NewAgendaButton.tsx, client/src/components/atoms/index.ts, client/src/components/molecules/AdminPreparingAgendaCard.tsx, client/src/components/molecules/Modal.tsx, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/molecules/index.ts, client/src/components/organisms/AdminAgendaSection.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx, client/src/components/pages/MainPage.tsx
Feat/admin preparing agenda UI 개발
=> Feat/admin preparing agenda UI

client/src/components/organisms/AdminAgendaSection.tsx, client/src/components/organisms/OngoingAgendaModal.tsx, client/src/components/pages/MainPage.tsx
main 페이지 '+새로운 투표' 버튼 누르면 CreateAgendaModal로 넘어갑니당
=> fix(preparing): navigate to CreateAgendaModal

client/src/components/molecules/OngoingAgendaCard.tsx
=> ongoind agenda card tags

client/src/components/atoms/CheckBox.tsx, client/src/components/atoms/index.ts, client/src/components/organisms/TerminatedAgendaModal.tsx
=> Checkbox UI

client/src/components/molecules/Choice.tsx, client/src/components/molecules/OngoingAgendaCard.tsx
=> feat(ui): add hover event to choice

client/src/components/molecules/index.ts, client/src/components/molecules/logoutButton.tsx, client/src/components/organisms/Header.tsx
=> feat(ui): add logout button in header

client/src/components/atoms/NewAddButton.tsx, client/src/components/atoms/Tag.tsx, client/src/components/atoms/UserTag.tsx, client/src/components/atoms/index.ts, client/src/components/molecules/AddButton.tsx, client/src/components/molecules/AdminOngoingAgendaCard.tsx, client/src/components/molecules/AdminPreparingAgendaCard.tsx, client/src/components/molecules/AdminTag.tsx, client/src/components/molecules/AdminTerminatedAgendaCard.tsx, client/src/components/molecules/AgendaTag.tsx, client/src/components/molecules/AgendaTemplateCards.tsx, client/src/components/molecules/UserTagCards.tsx, client/src/components/molecules/index.ts, client/src/components/organisms/AdminAgendaSection.tsx, client/src/components/organisms/AdminUserSection.tsx, client/src/components/organisms/AgendaSection.tsx, client/src/components/organisms/OngoingAgendaModal.tsx, client/src/components/organisms/index.ts, client/src/components/pages/AdminSettingPage.tsx, client/src/components/pages/AdminUserPage.tsx
=> Admin User Page ui 만들기

client/src/components/molecules/logoutButton.tsx, client/src/components/organisms/Header.tsx, client/src/services/auth.ts
=> feat(logout): navigate login page after logout

server/src/listener/admin.agenda.ts, server/src/service/chat.ts
dora가 시작/종료한 공지를 biseodevuser가 잘 받아요
=> Send notice on agenda start / terminate

client/src/components/molecules/Modal.tsx, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/CreateTemplateModal.tsx, client/src/components/organisms/EditTemplateModal.tsx
createTemplateModal에 직접 구현되어있던 부분을 공통으로 사용하고 있는 ModalInner 컴포넌트로 대체하였습니다.
=> feat(modal): use ModalInner in createTemplateModal

client/src/components/atoms/TextArea.tsx, client/src/components/molecules/ChatInput.tsx, client/src/components/molecules/Modal.tsx, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/molecules/ParticipantBar.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/CreateTemplateModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/EditTemplateModal.tsx, client/src/components/organisms/OngoingAgendaModal.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx
=> feat(textarea): add TextAreaFixedsize

client/src/components/atoms/TextArea.tsx, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/OngoingAgendaModal.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx
Resolves #185 
투표 대상 옆의 숫자도 수정되게 했엉요
=> fix(ui): user table width in modal

client/src/components/organisms/EditAgendaModal.tsx
=> fix(ui): remove unnecessary blue box

client/src/components/atoms/Text.tsx, client/src/components/molecules/ChatHeader.tsx, client/src/components/molecules/ChatInput.tsx, interface/src/chat/client.ts
Resolves #52 - done
Resolves #153 - done
Resolves #154 - done
Resolves #197 - done
Resolves #210 - done
=> Chat Issue Fix

client/src/components/atoms/Scroll.tsx, client/src/components/molecules/TerminatedAgendaModalInner.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx
=> feat(ui): vote result scroll in terminated agenda

client/src/components/molecules/AdminAgendaTags.tsx, client/src/components/molecules/Modal.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/CreateTemplateModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/OngoingAgendaModal.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx
=> fix(ui): button and modal size fix

client/src/components/organisms/CreateAgendaModal.tsx
=> feat(ui): add template apply button

client/src/components/molecules/ParticipantBar.tsx, client/src/components/molecules/TerminatedAgendaModalInner.tsx
=> fix(participantBar): remove NaN

client/src/components/atoms/Button.tsx, client/src/components/molecules/AgendaCard/AdminPreparingAgendaCard.tsx, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/CreateTemplateModal.tsx, client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/EditTemplateModal.tsx, client/src/components/organisms/EditUserTagModal.tsx, interface/src/admin/agenda/common.ts
Resolves #166
title, content, resolution, choices 비어있으면 투표 생성 / 수정 불가
title, content, resolution, choices, voters 비어있으면 투표 시작 불가
자잘한 refactor도 끼워져 있어요
choice 비어있는 string의 경우 validation 아직 안된 상태 -> 작업 완료 (Resolves #245)
=> Agenda input validation

client/src/components/organisms/AdminUserSection.tsx
=> fix(adminuser): template and usertag count

client/src/components/atoms/Box.tsx, client/src/components/atoms/Card.tsx, client/src/components/atoms/Scroll.tsx, client/src/components/atoms/index.ts, client/src/components/molecules/AgendaCard/EmptyAgendaCard.tsx, client/src/components/molecules/AgendaCard/OngoingAgendaCard.tsx, client/src/components/molecules/Message/List.tsx, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/organisms/AgendaSection.tsx, client/src/components/organisms/ChatSection.tsx, client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditUserTagModal.tsx, client/src/components/organisms/UserTable.tsx, client/src/components/pages/AdminAgendaPage.tsx, client/src/components/pages/AdminSettingPage.tsx, client/src/components/pages/MainPage.tsx, client/src/components/templates/PageLayout.tsx, client/src/index.css
Resolves #138, Resolves #136 
주요 변경사항
- 배경색 적용
- page height 끝까지 채우도록 함
- 페이지 세로 스크롤 behavior들 수정
자잘한 수정들
- `Box`에 `align`, `justify` prop 이상하게 설정되어있던거 고침 (~`git blame` -> `snowsuno`~)
- 기타등등 대충 보이는 문제들 쪼끔
=> Fix main page layout

client/src/components/atoms/Tag.tsx, client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx, client/src/components/molecules/VoteDetail.tsx, client/src/components/molecules/VoteParticipate.tsx, client/src/components/molecules/VoteResult.tsx, client/src/components/molecules/index.ts, client/src/components/organisms/AgendaSection.tsx
=> feat: add participant info in TerminatedAgendaCard + minor refactoring

client/src/components/organisms/EditTemplateModal.tsx
=> fix(template): count numbeers of vote options

client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/EditUserTagModal.tsx, client/src/components/organisms/UserTable.tsx, interface/src/user/tag/common.ts
=> User tag create/edit modal input validation

client/src/components/molecules/UserTagCards.tsx
=> fix(usertag): add suffix part

client/src/components/atoms/SelectBox.tsx, client/src/components/organisms/CreateAgendaModal.tsx, client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditAgendaModal.tsx, client/src/components/organisms/EditUserTagModal.tsx, client/src/components/organisms/OngoingAgendaModal.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx, client/src/components/organisms/UserTable.tsx
Resolves #276 
아 코드 좀 마음에 안드는데
=> User table filter type 투표 완료/미완료

client/src/components/molecules/AgendaTemplateCard.tsx
=> fix(template): show number of options of template

client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditUserTagModal.tsx, client/src/components/organisms/UserTable.tsx
=> Sort user table by username

client/src/components/atoms/TaggersBox.tsx, client/src/components/atoms/index.ts, client/src/components/molecules/ModalInnerTextBox.tsx, client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditUserTagModal.tsx
resolve #248 
usertable이랑 ui 동일하게 스크롤은 숨겼습니당
**Before**
**After**
=> fix(modal): taggers display part scroll

server/src/service/agenda.ts
=> feat(agenda-voted): fix emit voted

client/src/components/organisms/UserTable.tsx
=> fix: user table header checkbox logic

client/src/components/molecules/AgendaCard/AdminOngoingAgendaCard.tsx, client/src/components/molecules/AgendaCard/AdminPreparingAgendaCard.tsx, client/src/components/molecules/AgendaCard/AdminTerminatedAgendaCard.tsx, client/src/components/molecules/AgendaCard/OngoingAgendaCard.tsx, client/src/components/molecules/AgendaCard/PreparingAgendaCard.tsx, client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx
=> feat(tag): private to public

client/src/components/organisms/AgendaSection.tsx
=> feat(logic): unvoted agenda on top

client/src/components/atoms/Table.tsx, client/src/components/organisms/UserTable.tsx
=> fix(usertable): apply Scroll component

client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx, client/src/components/molecules/VoteResult.tsx
=> fix(Ter-Agenda): only voted voters see result

client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx, client/src/components/molecules/OptionVoteResult.tsx, client/src/components/molecules/ParticipantBar.tsx, client/src/components/molecules/TerminatedAgendaModalInner.tsx, client/src/components/organisms/TerminatedAgendaModal.tsx
Resolves #251 
종료된 투표에 보이는 투표 결과랑
어드민 진행중 투표에 보이는 진행률수정했습니다.
=> fix(vote-result): fix graph UI

client/src/components/atoms/HyperText.tsx, client/src/components/atoms/index.ts, client/src/components/molecules/Message/PlainMessage.tsx
=> 채팅에서 하이퍼텍스트 기능

client/src/components/organisms/CreateUserTagModal.tsx, client/src/components/organisms/EditUserTagModal.tsx, client/src/components/organisms/Header.tsx
=> 헤더 탭 가림 & 태그 패딩 이슈 해결

client/src/components/atoms/BorderedBox.tsx, client/src/components/atoms/Box.tsx, client/src/components/atoms/HyperText.tsx, client/src/components/atoms/Text.tsx
=> Mark deprecated atom components

client/src/components/atoms/Scroll.tsx, client/src/components/molecules/AgendaCard/Group.tsx, client/src/components/molecules/AgendaCard/List.tsx, client/src/components/molecules/AgendaCard/index.tsx, client/src/components/molecules/SectionHeader.tsx, client/src/components/organisms/AgendaSection.tsx, client/src/styles/index.ts, client/src/styles/scroll.ts
=> Refactor agenda section layout

client/src/components/molecules/AgendaCard/AdminOngoingAgendaCard.tsx, client/src/components/molecules/AgendaCard/AdminPreparingAgendaCard.tsx, client/src/components/molecules/AgendaCard/AdminTerminatedAgendaCard.tsx, client/src/components/molecules/AgendaCard/EmptyAgendaCard.tsx, client/src/components/molecules/AgendaCard/OngoingAgendaCard.tsx, client/src/components/molecules/AgendaCard/PreparingAgendaCard.tsx, client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx
=> AgendaCard CSS Styling refactor

client/src/components/organisms/AgendaSection.tsx
Fixes #357 
#373에서 코멘트에 언급되었던 내용대로 간단히 수정되어서 해당 내용 바탕으로 다시 PR 열었습니당
레이아웃 깨지지 않는지 한번씩 체크 부탁드려요
=> Fix agenda section grid layout

client/src/components/molecules/AgendaCard/AdminOngoingAgendaCard.tsx, client/src/components/molecules/AgendaCard/AdminPreparingAgendaCard.tsx, client/src/components/molecules/AgendaCard/AdminTerminatedAgendaCard.tsx, client/src/components/molecules/AgendaCard/OngoingAgendaCard.tsx, client/src/components/molecules/AgendaCard/PreparingAgendaCard.tsx, client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx
Fixes #358 
#370 이랑 겹치는 내용이 조금 있긴 한데 오늘 급히 시연이 있어서 이 부분만 급히 따로 빼서 슥 고쳤습니다
=> Add unapplied column gaps

client/src/components/molecules/AgendaCard/EmptyAgendaCard.tsx, client/src/components/molecules/AgendaCard/Group.tsx, client/src/components/organisms/AgendaSection.tsx, client/src/constants/phrases.ts
투표가 0개인 섹션이 투표 1개로 표시되는 버그를 해결합니다
+ 약간의 리팩토링
=> Fix agenda numbers

client/src/components/atoms/Label.tsx, client/src/components/pages/LoginPage.tsx, client/src/index.css
Input, select 등에서의 placeholder에 폰트가 제대로 표시되지 않는 문제를 해결합니다.
=> Fix placeholder fonts

client/src/components/molecules/AgendaCard/TerminatedAgendaCard.tsx
Fixes #358 
#379 에서 고쳐지지 않은 부분 수정사항입니다
=> Fix terminated agenda card gap

.husky/pre-commit
=> Fix commit error

packages/web/src/components/organisms/CreateUserTagModal.tsx, packages/web/src/components/organisms/EditUserTagModal.tsx
=> fix(usertag): change InputBox to TextAreaInputBox

packages/web/src/components/organisms/EditTemplateModal.tsx
=> fix(template): change InputBox to TextAreaInputBox

packages/web/src/components/atoms/Button.tsx, packages/web/src/components/atoms/Label.tsx, packages/web/src/components/atoms/SelectBox.tsx, packages/web/src/components/atoms/placeholder.css, packages/web/src/components/molecules/UserTagCards.tsx, packages/web/src/components/organisms/CreateUserTagModal.tsx
=> Feat/tag modal UI

packages/api/src/service/agenda.ts
투표 이벤트가 admin이 아닌 다른 유저에게 전송되는 이슈를 수정합니다. 
- 없음
=> `admin.agenda.voted`의 emit scope 제한

packages/web/src/components/molecules/AdminAgendaTags.tsx
It closes [#467 ](https://github.com/sparcs-kaist/biseo/issues/467)
Align 정렬하기
- 없음
=> feat: align tags center

packages/api/src/service/chat.ts
=> feat: anonymous chatting

packages/web/package.json, pnpm-lock.yaml
dependency package 추가 (lucide-react & react-oauth/google
=> feat: add lucide-react and react-oauth/google

packages/web/src/components/pages/LoginPage.tsx
=> fix: background image touch error
